name: lint

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: unstall uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: lint
        run: make lint
